### ISSUE TITLE
[SST-8] Commands and queries

### ISSUE THREAD

**Issue by DthRazak** [DthRazak/Student-Success-Tracking#15]
Write the commands and queries

**Comment by DthRazak** [comment]
Commands for @Calvados0806:
- UpdateUserCommand
- DeleteUserCommand
- UpdateStudentCommand
- DeleteStudentCommand
- CreateStudentCommand
- UpdateLectorCommand
- DeleteLectorCommand
- CreateLectorCommand
- UpdateRequestCommand
- DeleteRequestCommand

**Comment by DthRazak** [comment]
Queries for @Oksana-Pylypovych:
- GetLectorsQuery
- GetStudentsQuery
- GetUsersQuery
- GetRequestsQuery
- GetNotApprovedRequestsQuery

**Comment by DthRazak** [comment]
@Calvados0806 all classes that you realized must be public, fix it

**Comment by Calvados0806** [comment]
@DthRazak. Fixed that. Please see commit: [f78b4f97eb66e0c48bdc7ca884ac49b2cc8bec52](https://github.com/DthRazak/Student-Success-Tracking/commit/f78b4f97eb66e0c48bdc7ca884ac49b2cc8bec52)
